version: 2

sources:
  - name: airbytes_test
    description: "testing airbytes using dbt"
    database: airbytes_test
    schema: country
    tables:
      - name: airbytesuser
        description: "details about user"

